aliyun-oss:
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  base-path: yourBasePath
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  endpoint: yourEndpoint
autocode:
  root: ""
  server: /server
  server-api: /api/v1/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-request: /model/%s/request/
  server-router: /router/%s
  server-service: /service/%s
  transfer-restart: true
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view
aws-s3:
  base-url: https://gin.vue.admin
  bucket: xxxxx-10005608
  disable-ssl: false
  endpoint: ""
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
  region: ap-shanghai
  s3-force-path-style: false
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
captcha:
  img-height: 80
  img-width: 240
  key-long: 6
casbin:
  model-path: ./resource/rbac_model.conf
cors:
  mode: whitelist
  whitelist:
  - allow-credentials: true
    allow-headers: content-type
    allow-methods: GET, POST
    allow-origin: example1.com
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
  - allow-credentials: true
    allow-headers: content-type
    allow-methods: GET, POST
    allow-origin: example2.com
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
db-list:
- alias-name: ""
  config: ""
  db-name: ""
  disabled: true
  log-mode: ""
  log-zap: false
  max-idle-conns: 10
  max-open-conns: 100
  password: ""
  path: ""
  port: ""
  type: ""
  username: ""
email:
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  nickname: test
  port: 465
  secret: xxx
  to: xxx@qq.com
excel:
  dir: ./resource/excel/
hua-wei-obs:
  access-key: you-access-key
  bucket: you-bucket
  endpoint: you-endpoint
  path: you-path
  secret-key: you-secret-key
jwt:
  buffer-time: 86400
  expires-time: 604800
  issuer: qmPlus
  signing-key: 418440b2-8f4f-4366-b3bb-45f4d45dfeca
local:
  path: uploads/file
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gva
  username: root
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
pgsql:
  config: ""
  db-name: ""
  log-mode: ""
  log-zap: false
  max-idle-conns: 10
  max-open-conns: 100
  password: ""
  path: ""
  port: ""
  username: ""
qiniu:
  access-key: ""
  bucket: ""
  img-path: ""
  secret-key: ""
  use-cdn-domains: false
  use-https: false
  zone: ZoneHuaDong
redis:
  addr: 127.0.0.1:6379
  db: 0
  password: ""
system:
  addr: 8888
  db-type: mysql
  env: public
  iplimit-count: 15000
  iplimit-time: 3600
  oss-type: local
  use-multipoint: false
  use-redis: false
tencent-cos:
  base-url: https://gin.vue.admin
  bucket: xxxxx-10005608
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
  region: ap-shanghai
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
timer:
  detail:
  - compareField: created_at
    interval: 2160h
    tableName: sys_operation_records
  - compareField: created_at
    interval: 168h
    tableName: jwt_blacklists
  spec: '@daily'
  start: true
zap:
  director: log
  encode-level: LowercaseColorLevelEncoder
  format: console
  level: info
  log-in-console: true
  prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
  show-line: true
  stacktrace-key: stacktrace
